<?php
/**
* @file
* change start up value of jCarousel
*/

/**
 * Implements hook_views_pre_view().
 */
function civipartnerblock_views_pre_view(&$view, &$display_id, &$args) {
  $civipartnerblock_displayedorgids = 0;
  $civipartnerblock_lastrefreshdate = date('d/m/Y');
  $startvalue = 1;
  if (isset($view->name) && $view->name == 'rotating_partner_logos') {
    //get value of civipartnerblock_displayedorgids,civipartnerblock_lastrefreshdate variable
    $civipartnerblock_displayedorgids = variable_get('civipartnerblock_displayedorgids');
    $civipartnerblock_lastrefreshdate = variable_get('civipartnerblock_lastrefreshdate');
    //get result value of view
    $view->render();
    $view_result = $view->result;
    $view_total_row = sizeof($view_result);

    foreach ($view_result as $key => $value) {
      $view_result[$key] = (array) $value;
      $result_detail[$key] = $value->id;
    }

    if (empty($civipartnerblock_displayedorgids)) {
      //if civipartnerblock_displayedorgids is empty take first value of view result
      $first_record = reset($view_result);
      $civipartnerblock_displayedorgids[$first_record['id']] = $first_record['id'];
    }
    else {
      if ($civipartnerblock_lastrefreshdate < date('d/m/Y')) {
        if (count($civipartnerblock_displayedorgids) == count($view_result)) {
          $civipartnerblock_displayedorgids = array();
        }
        foreach ($view_result as $key => $values) {
          if (in_array($values['id'] , $civipartnerblock_displayedorgids)) {
            continue;
          }
          else {
            $civipartnerblock_displayedorgids[$values['id']] = $values['id'];
            break;
          }
        }
      }
    }
    if (!empty($civipartnerblock_displayedorgids)) {
      $startvalue = array_search(end($civipartnerblock_displayedorgids) , $result_detail) + 1;
    }

    //set value of civipartnerblock_displayedorgids,civipartnerblock_lastrefreshdate variable
    variable_set('civipartnerblock_displayedorgids', $civipartnerblock_displayedorgids);
    variable_set('civipartnerblock_lastrefreshdate', date('d/m/Y'));
    //set start value of jCarousel slider
    $view->display['default']->display_options['style_options']['start'] = $startvalue;
    views_save_view($view);
  }
}