a:3:{s:5:"child";a:1:{s:27:"http://www.w3.org/2005/Atom";a:1:{s:4:"feed";a:1:{i:0;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:36:"http://www.w3.org/XML/1998/namespace";a:2:{s:4:"base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:4:"lang";s:5:"en-gb";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";s:5:"child";a:1:{s:27:"http://www.w3.org/2005/Atom";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:53:"Joomla! Developer - CiviCRM: Aesthetics and Usability";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"text";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:8:"subtitle";a:1:{i:0;a:5:{s:4:"data";s:274:"Not only is Joomla! easy to use, but it is easy to add extra functionality through a flexible and powerful developer framework. The Joomla! Framework allows you to build exceptional extensions for Joomla! including components, modules, plugins, templates and language packs.";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"text";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:4:"link";a:2:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:3:{s:3:"rel";s:9:"alternate";s:4:"type";s:9:"text/html";s:4:"href";s:47:"/gsoc2008/civicrm-aesthetics-and-usability.html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}i:1;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:3:{s:3:"rel";s:4:"self";s:4:"type";s:20:"application/atom+xml";s:4:"href";s:1:"/";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:2:"id";a:1:{i:0;a:5:{s:4:"data";s:47:"/gsoc2008/civicrm-aesthetics-and-usability.html";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"updated";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-10-25T00:20:11Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:9:"generator";a:1:{i:0;a:5:{s:4:"data";s:44:"Joomla! 1.5 - Open Source Content Management";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"uri";s:17:"http://joomla.org";s:7:"version";s:3:"1.5";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:5:"entry";a:7:{i:0;a:6:{s:4:"data";s:23:"
		
		
		
		
		
		
		
	";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";s:5:"child";a:1:{s:27:"http://www.w3.org/2005/Atom";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:29:"Full steam ahead ... finally.";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:3:{s:3:"rel";s:9:"alternate";s:4:"type";s:9:"text/html";s:4:"href";s:77:"/gsoc2008/civicrm-aesthetics-and-usability/160-full-steam-ahead--finally.html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:9:"published";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-06-28T20:52:34Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"updated";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-06-28T20:52:34Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:2:"id";a:1:{i:0;a:5:{s:4:"data";s:77:"/gsoc2008/civicrm-aesthetics-and-usability/160-full-steam-ahead--finally.html";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"summary";a:1:{i:0;a:5:{s:4:"data";s:962:"<p>&nbsp;Hey everyone,</p>
<p>Some technical issues sidelined me for a bit, as Linux, my PC, and code issues stalled my progress. That's what makes this endeavor exciting though, right?</p>
<p>Anyway, in the next week, I hope to get some changes implemented in the menus, starting with Drupal and working my way through. The hope is that the menu layout will remain the same in Drupal, Joomla! and the Standalone with the changes being to the look and feel of the menu.</p>
<p><img alt="Menu System" align="right" border="2px" vspace="px" hspace="px" style="padding: 2px;" src="http://jtv79.com/GSoC/menusystem.png" /></p>
<p>I have already done some preliminary work on the menus and I have an idea of how I see the changes being implemented. Now, it's time to dig into the code and make the changes work within CiviCRM. The plan is to have a sandbox up with the menu changes implemented by the end of the week so I can gather feedback on the changes.&nbsp;</p>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"content";a:1:{i:0;a:5:{s:4:"data";s:962:"<p>&nbsp;Hey everyone,</p>
<p>Some technical issues sidelined me for a bit, as Linux, my PC, and code issues stalled my progress. That's what makes this endeavor exciting though, right?</p>
<p>Anyway, in the next week, I hope to get some changes implemented in the menus, starting with Drupal and working my way through. The hope is that the menu layout will remain the same in Drupal, Joomla! and the Standalone with the changes being to the look and feel of the menu.</p>
<p><img alt="Menu System" align="right" border="2px" vspace="px" hspace="px" style="padding: 2px;" src="http://jtv79.com/GSoC/menusystem.png" /></p>
<p>I have already done some preliminary work on the menus and I have an idea of how I see the changes being implemented. Now, it's time to dig into the code and make the changes work within CiviCRM. The plan is to have a sandbox up with the menu changes implemented by the end of the week so I can gather feedback on the changes.&nbsp;</p>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}}}}i:1;a:6:{s:4:"data";s:23:"
		
		
		
		
		
		
		
	";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";s:5:"child";a:1:{s:27:"http://www.w3.org/2005/Atom";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:14:"Piece by piece";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:3:{s:3:"rel";s:9:"alternate";s:4:"type";s:9:"text/html";s:4:"href";s:66:"/gsoc2008/civicrm-aesthetics-and-usability/141-piece-by-piece.html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:9:"published";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-06-16T04:18:18Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"updated";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-06-16T04:18:18Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:2:"id";a:1:{i:0;a:5:{s:4:"data";s:66:"/gsoc2008/civicrm-aesthetics-and-usability/141-piece-by-piece.html";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"summary";a:1:{i:0;a:5:{s:4:"data";s:826:"<p>As I move into actually implementing some of the standards I have been finalizing, I wanted to thank everyone for their feedback so far. Moving forward, I am planning to tackle my project piece by piece as the summer progresses.</p>
<p>Now that I have some standards in place, I am going to work on getting a new menu established. Keys to this included identifying what is missing and/or extra on the current menus.</p>
<p>I plan on implementing a horizontal menu. I also plan on ensuring that any necessary links are present above the &quot;fold&quot; of the page, making it so users do not have to scroll down to access options. Hopefully, some rough implementation of this will be done soon.</p>
<p>After the menu, I'll take some time and brush up the standards documentation before moving onto the next piece.&nbsp;</p>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"content";a:1:{i:0;a:5:{s:4:"data";s:826:"<p>As I move into actually implementing some of the standards I have been finalizing, I wanted to thank everyone for their feedback so far. Moving forward, I am planning to tackle my project piece by piece as the summer progresses.</p>
<p>Now that I have some standards in place, I am going to work on getting a new menu established. Keys to this included identifying what is missing and/or extra on the current menus.</p>
<p>I plan on implementing a horizontal menu. I also plan on ensuring that any necessary links are present above the &quot;fold&quot; of the page, making it so users do not have to scroll down to access options. Hopefully, some rough implementation of this will be done soon.</p>
<p>After the menu, I'll take some time and brush up the standards documentation before moving onto the next piece.&nbsp;</p>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}}}}i:2;a:6:{s:4:"data";s:23:"
		
		
		
		
		
		
		
	";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";s:5:"child";a:1:{s:27:"http://www.w3.org/2005/Atom";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:30:"Further forays into standards.";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:3:{s:3:"rel";s:9:"alternate";s:4:"type";s:9:"text/html";s:4:"href";s:81:"/gsoc2008/civicrm-aesthetics-and-usability/117-further-forays-into-standards.html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:9:"published";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-06-04T05:30:05Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"updated";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-06-04T05:30:05Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:2:"id";a:1:{i:0;a:5:{s:4:"data";s:81:"/gsoc2008/civicrm-aesthetics-and-usability/117-further-forays-into-standards.html";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"summary";a:1:{i:0;a:5:{s:4:"data";s:1718:"<p>Thanks. That's the first thing I want to say. Between here, the <a href="http://wiki.civicrm.org/confluence/display/CRM/GSoC+Project+-+Aesthetics+and+Usability">CiviCRM wiki</a>, the <a href="http://forum.civicrm.org/index.php">CiviCRM forums</a> and the <a href="http://civicrm.org/blog/">CiviCRM blog</a>, all the comments and feedback have been wonderful. It's been great engaging the community and I hope this is the start and not the end.</p>
<p>Thanks to some peer reviews and all the feedback I continue to receive, I have spent the last week trying to begin the documentation process. Quick, define aethetics... how about usability? *crickets chirping*</p>
<p>These can be very personal things and it can be hard as an organization to define standards and be firm about them. So, I have been researching aethetics and usability. I've been also trying to ensure I document everything in a logical fashion. This will make the changes I implement easier and make it easier for future development to follow.</p>
<p>To that end, so far so good. The wiki has a solid framework that I will work on fleshing out through this week. By the end of the weekend, I hope to have the standards largely done. Or at least in place and ready to be audited and adapted as needed.</p>
<p>My project this summer will then shift its focus to working on the navigation within CiviCRM and the home page look. I'll hopefully be doing some mockups and identifying issues with usability and aesthetics as able.</p>
<p>Comments, suggestions and feedback are greatly appreciated. Oh, and finding things <a href="http://www.alistapart.com/articles/writingainterfacestyleguide">like this on a List Apart</a> this week is so wonderful.</p>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"content";a:1:{i:0;a:5:{s:4:"data";s:1718:"<p>Thanks. That's the first thing I want to say. Between here, the <a href="http://wiki.civicrm.org/confluence/display/CRM/GSoC+Project+-+Aesthetics+and+Usability">CiviCRM wiki</a>, the <a href="http://forum.civicrm.org/index.php">CiviCRM forums</a> and the <a href="http://civicrm.org/blog/">CiviCRM blog</a>, all the comments and feedback have been wonderful. It's been great engaging the community and I hope this is the start and not the end.</p>
<p>Thanks to some peer reviews and all the feedback I continue to receive, I have spent the last week trying to begin the documentation process. Quick, define aethetics... how about usability? *crickets chirping*</p>
<p>These can be very personal things and it can be hard as an organization to define standards and be firm about them. So, I have been researching aethetics and usability. I've been also trying to ensure I document everything in a logical fashion. This will make the changes I implement easier and make it easier for future development to follow.</p>
<p>To that end, so far so good. The wiki has a solid framework that I will work on fleshing out through this week. By the end of the weekend, I hope to have the standards largely done. Or at least in place and ready to be audited and adapted as needed.</p>
<p>My project this summer will then shift its focus to working on the navigation within CiviCRM and the home page look. I'll hopefully be doing some mockups and identifying issues with usability and aesthetics as able.</p>
<p>Comments, suggestions and feedback are greatly appreciated. Oh, and finding things <a href="http://www.alistapart.com/articles/writingainterfacestyleguide">like this on a List Apart</a> this week is so wonderful.</p>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}}}}i:3;a:6:{s:4:"data";s:23:"
		
		
		
		
		
		
		
	";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";s:5:"child";a:1:{s:27:"http://www.w3.org/2005/Atom";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:44:"A stab at standards. CiviCRM: look and feel.";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:3:{s:3:"rel";s:9:"alternate";s:4:"type";s:9:"text/html";s:4:"href";s:93:"/gsoc2008/civicrm-aesthetics-and-usability/108-a-stab-at-standards-civicrm-look-and-feel.html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:9:"published";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-05-28T05:54:23Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"updated";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-05-28T05:54:23Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:2:"id";a:1:{i:0;a:5:{s:4:"data";s:93:"/gsoc2008/civicrm-aesthetics-and-usability/108-a-stab-at-standards-civicrm-look-and-feel.html";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"summary";a:1:{i:0;a:5:{s:4:"data";s:5445:"<h2>&nbsp;<span class="Apple-style-span" style="font-family: Helvetica; line-height: normal; ">Standards and Requirements</span></h2>
<div>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">Currently, the base installation of CiviCRM lacks a cohesive look across different platforms. The Drupal, Joomla! and Standalone versions lack a visual cohesiveness that would aid in establishing an identity and easing user interaction.&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">The home page for a CiviCRM installation presents the user with either a vertical or a horizontal menu bar, with a secondary vertical menu underneath. Dependent on the platform and the user's screen resolution, these menus can extend beyond the first screen presented to the end user, resulting in the user having to scroll both horizontally and vertically to access the options.</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">The base installation for CiviCRM needs to embrace a consistent look across platforms. Whether hosted in Drupal, Joomla! or used as a Standalone, the usability and design needs to remain the same. To that end, some standards and requirements have to be implemented into CiviCRM.</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<h3>1. Identity</h3>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">An identity that is portable and easy to use within the different installation options is vital. Use of the CiviCRM logo is the ideal solution; however, even mimicking just the text from the logo, with the word 'civi' bold followed by CRM in normal typeface, would aid brand identity.</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">Additionally, aiding user migration between platforms by ensuring a cohesive look and feel to CiviCRM would ensure that CiviCRM provided the same experience without being dependent on its platform.&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<h3>2. Menu Layout</h3>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">A consistent top menu across platforms and screen resolutions is necessary. Starting with a base resolution of 800 x 600 and working out takes a majority of end users into consideration. The&nbsp; final look must ensure that any technological requirements, such as images, javascript, et. al, degrade gracefully as required by user settings/preferences.</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">To this end, the final design requires a more compact and fluid navigational menu. Giving the user the ability to customize this menu allows the reordering and/or removing of options without alienating the installation base. Following a tighter menu to submenu trail from the home page ensures satisfaction of the standards while taking users into consideration.&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<h3>3. Home Page</h3>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">The initial home page needs to follow the lead of the top menu, providing the user with a tight, visually consistent experience across platforms. The home page also needs to take technological limitations into consideration.</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<h3>4. Sub-pages</h3>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">Modules to allow customization and swappable components. Utilizing a basic template allows the end user the ability to customize the theme. This could be achieved through something as simple as a color picker for the modules or a more complex user assembled puzzle piece approach to the template.</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<h3>5. Special Considerations</h3>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">A solid and flexible framework for any changes helps to address any special considerations. It facilitates that the changes gracefully handle all major browsers with additional support for deprecated versions. It would also handle any possible accessibility issues, addressing concerns that arise from screen readers, scanning software and other methodology.</p>
</div>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"content";a:1:{i:0;a:5:{s:4:"data";s:5445:"<h2>&nbsp;<span class="Apple-style-span" style="font-family: Helvetica; line-height: normal; ">Standards and Requirements</span></h2>
<div>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">Currently, the base installation of CiviCRM lacks a cohesive look across different platforms. The Drupal, Joomla! and Standalone versions lack a visual cohesiveness that would aid in establishing an identity and easing user interaction.&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">The home page for a CiviCRM installation presents the user with either a vertical or a horizontal menu bar, with a secondary vertical menu underneath. Dependent on the platform and the user's screen resolution, these menus can extend beyond the first screen presented to the end user, resulting in the user having to scroll both horizontally and vertically to access the options.</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">The base installation for CiviCRM needs to embrace a consistent look across platforms. Whether hosted in Drupal, Joomla! or used as a Standalone, the usability and design needs to remain the same. To that end, some standards and requirements have to be implemented into CiviCRM.</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<h3>1. Identity</h3>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">An identity that is portable and easy to use within the different installation options is vital. Use of the CiviCRM logo is the ideal solution; however, even mimicking just the text from the logo, with the word 'civi' bold followed by CRM in normal typeface, would aid brand identity.</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">Additionally, aiding user migration between platforms by ensuring a cohesive look and feel to CiviCRM would ensure that CiviCRM provided the same experience without being dependent on its platform.&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<h3>2. Menu Layout</h3>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">A consistent top menu across platforms and screen resolutions is necessary. Starting with a base resolution of 800 x 600 and working out takes a majority of end users into consideration. The&nbsp; final look must ensure that any technological requirements, such as images, javascript, et. al, degrade gracefully as required by user settings/preferences.</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">To this end, the final design requires a more compact and fluid navigational menu. Giving the user the ability to customize this menu allows the reordering and/or removing of options without alienating the installation base. Following a tighter menu to submenu trail from the home page ensures satisfaction of the standards while taking users into consideration.&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<h3>3. Home Page</h3>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">The initial home page needs to follow the lead of the top menu, providing the user with a tight, visually consistent experience across platforms. The home page also needs to take technological limitations into consideration.</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<h3>4. Sub-pages</h3>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">Modules to allow customization and swappable components. Utilizing a basic template allows the end user the ability to customize the theme. This could be achieved through something as simple as a color picker for the modules or a more complex user assembled puzzle piece approach to the template.</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<h3>5. Special Considerations</h3>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px">&nbsp;</p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica">A solid and flexible framework for any changes helps to address any special considerations. It facilitates that the changes gracefully handle all major browsers with additional support for deprecated versions. It would also handle any possible accessibility issues, addressing concerns that arise from screen readers, scanning software and other methodology.</p>
</div>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}}}}i:4;a:6:{s:4:"data";s:23:"
		
		
		
		
		
		
		
	";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";s:5:"child";a:1:{s:27:"http://www.w3.org/2005/Atom";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:46:"Establishing contact and facilitating feedback";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:3:{s:3:"rel";s:9:"alternate";s:4:"type";s:9:"text/html";s:4:"href";s:98:"/gsoc2008/civicrm-aesthetics-and-usability/107-establishing-contact-and-facilitating-feedback.html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:9:"published";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-05-28T05:49:31Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"updated";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-05-28T05:49:31Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:2:"id";a:1:{i:0;a:5:{s:4:"data";s:98:"/gsoc2008/civicrm-aesthetics-and-usability/107-establishing-contact-and-facilitating-feedback.html";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"summary";a:1:{i:0;a:5:{s:4:"data";s:1536:"<p>&nbsp;Is it really time to get this party started? It seems like just yesterday that I was accepted into the Summer of Code and now, here we are, beginning the summer in earnest. This is also where everyone else comes in.</p>
<div>&nbsp;</div>
<div>Over the last month or so, I have been introducing myself to CiviCRM and its visual identity. As part of this first phase, I want to hear from the developers and the users of CiviCRM. What about its aesthetics and usability is good? What is bad?</div>
<div>&nbsp;</div>
<div>As I begin to draft new documentation in regards to CiviCRM's usability and aesthetics, I am hoping to engage them through here, the <a href="http://wiki.civicrm.org/confluence/display/CRM/GSoC+Project+-+Aesthetics+and+Usability">CiviCRM wiki</a> and the <a href="http://forum.civicrm.org/index.php/topic,3486.0.html">CiviCRM forums</a>.&nbsp;</div>
<div>&nbsp;</div>
<div>While I refine the documentation and garner feedback, I am also subjecting myself to a peer review. The created documentation and my plans for the summer will be presented to someone unassociated with the project in hopes of getting a fair and balanced assessment of my project. This individual is an industry professional in regards to project management, business analysis and technical writing.</div>
<div>&nbsp;</div>
<div>My success this summer hinges on community feedback and strong, well-defined documentation. I hope to establish this within the next two weeks and utilize these two items throughout the project duration.</div>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"content";a:1:{i:0;a:5:{s:4:"data";s:1536:"<p>&nbsp;Is it really time to get this party started? It seems like just yesterday that I was accepted into the Summer of Code and now, here we are, beginning the summer in earnest. This is also where everyone else comes in.</p>
<div>&nbsp;</div>
<div>Over the last month or so, I have been introducing myself to CiviCRM and its visual identity. As part of this first phase, I want to hear from the developers and the users of CiviCRM. What about its aesthetics and usability is good? What is bad?</div>
<div>&nbsp;</div>
<div>As I begin to draft new documentation in regards to CiviCRM's usability and aesthetics, I am hoping to engage them through here, the <a href="http://wiki.civicrm.org/confluence/display/CRM/GSoC+Project+-+Aesthetics+and+Usability">CiviCRM wiki</a> and the <a href="http://forum.civicrm.org/index.php/topic,3486.0.html">CiviCRM forums</a>.&nbsp;</div>
<div>&nbsp;</div>
<div>While I refine the documentation and garner feedback, I am also subjecting myself to a peer review. The created documentation and my plans for the summer will be presented to someone unassociated with the project in hopes of getting a fair and balanced assessment of my project. This individual is an industry professional in regards to project management, business analysis and technical writing.</div>
<div>&nbsp;</div>
<div>My success this summer hinges on community feedback and strong, well-defined documentation. I hope to establish this within the next two weeks and utilize these two items throughout the project duration.</div>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}}}}i:5;a:6:{s:4:"data";s:23:"
		
		
		
		
		
		
		
	";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";s:5:"child";a:1:{s:27:"http://www.w3.org/2005/Atom";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:38:"Team: CiviCRM Aesthetics and Usability";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:3:{s:3:"rel";s:9:"alternate";s:4:"type";s:9:"text/html";s:4:"href";s:88:"/gsoc2008/civicrm-aesthetics-and-usability/33-team-civicrm-aesthetics-and-usability.html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:9:"published";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-04-24T21:05:44Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"updated";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-04-24T21:05:44Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:2:"id";a:1:{i:0;a:5:{s:4:"data";s:88:"/gsoc2008/civicrm-aesthetics-and-usability/33-team-civicrm-aesthetics-and-usability.html";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"summary";a:1:{i:0;a:5:{s:4:"data";s:1636:"<p><img alt="Jon Volkman" src="images/stories/gsoc2008/jon.jpg" class="photoleft" /></p>
<div id="photoclear"></div>
<p>Jon Volkman is a student from Seattle working towards a certificate in software testing and quality assurance. He holds two associate degrees, one in web design and another in database management. Jon has a solid set of skills in CSS, HTML, and PHP and is familar with Linux, Mac OSX and Windows and PC hardware. Jon is a trained <a href="http://en.wikipedia.org/wiki/Barista">barista</a> who has spent the last two years doing quality assurance on a wide variety of Xbox, PS3 and PC games. Jon enjoys reading a wide range of books, exploring Seattle and the surrounding area, finding new vegetarian delicacies and hanging out with friends.</p>
<p><img alt="Wes Morgan" src="images/stories/gsoc2008/wes.jpg" class="photoright" /> <i>Mentor: </i>Wes Morgan is an online organizer and software developer for <a href="http://www.environmentamerica.org/">Environment America</a>. He works to get people involved in environmental advocacy in their backyard and across the US. He is also a user and contributor to open source software like <a href="http://www.webgui.org/">WebGUI</a> and <a href="http://www.civicrm.org/">CiviCRM</a>. This summer, he is working with the Joomla! GSoC team to mentor projects relating to CiviCRM (CiviCRM integrates with Joomla!). When not working or coding, Wes enjoys spending time in the Colorado Rocky Mountains hiking or skiing, and/or sampling the many delicious microbrews of the Front Range. You'll also often find him running through the park (and only sometimes being chased).</p>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"content";a:1:{i:0;a:5:{s:4:"data";s:1636:"<p><img alt="Jon Volkman" src="images/stories/gsoc2008/jon.jpg" class="photoleft" /></p>
<div id="photoclear"></div>
<p>Jon Volkman is a student from Seattle working towards a certificate in software testing and quality assurance. He holds two associate degrees, one in web design and another in database management. Jon has a solid set of skills in CSS, HTML, and PHP and is familar with Linux, Mac OSX and Windows and PC hardware. Jon is a trained <a href="http://en.wikipedia.org/wiki/Barista">barista</a> who has spent the last two years doing quality assurance on a wide variety of Xbox, PS3 and PC games. Jon enjoys reading a wide range of books, exploring Seattle and the surrounding area, finding new vegetarian delicacies and hanging out with friends.</p>
<p><img alt="Wes Morgan" src="images/stories/gsoc2008/wes.jpg" class="photoright" /> <i>Mentor: </i>Wes Morgan is an online organizer and software developer for <a href="http://www.environmentamerica.org/">Environment America</a>. He works to get people involved in environmental advocacy in their backyard and across the US. He is also a user and contributor to open source software like <a href="http://www.webgui.org/">WebGUI</a> and <a href="http://www.civicrm.org/">CiviCRM</a>. This summer, he is working with the Joomla! GSoC team to mentor projects relating to CiviCRM (CiviCRM integrates with Joomla!). When not working or coding, Wes enjoys spending time in the Colorado Rocky Mountains hiking or skiing, and/or sampling the many delicious microbrews of the Front Range. You'll also often find him running through the park (and only sometimes being chased).</p>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}}}}i:6;a:6:{s:4:"data";s:23:"
		
		
		
		
		
		
		
	";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";s:5:"child";a:1:{s:27:"http://www.w3.org/2005/Atom";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:42:"Abstract: CiviCRM Aesthetics and Usability";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:3:{s:3:"rel";s:9:"alternate";s:4:"type";s:9:"text/html";s:4:"href";s:92:"/gsoc2008/civicrm-aesthetics-and-usability/14-abstract-civicrm-aesthetics-and-usability.html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:9:"published";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-04-23T04:18:19Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"updated";a:1:{i:0;a:5:{s:4:"data";s:20:"2008-04-23T04:18:19Z";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:2:"id";a:1:{i:0;a:5:{s:4:"data";s:92:"/gsoc2008/civicrm-aesthetics-and-usability/14-abstract-civicrm-aesthetics-and-usability.html";s:7:"attribs";a:0:{}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"summary";a:1:{i:0;a:5:{s:4:"data";s:2191:"<blockquote>&quot;CiviCRM works great, but its visual design and layout could be better. Joomla! has great aesthetics and usability which would greatly benefit CiviCRM.&quot;</blockquote>
<p>&nbsp;</p>
<p>Integration will be a key to improving CiviCRM. Not only does it need to have its own distinct design, but it needs to integrate into Joomla! and feel as if it belongs. Integration of Joomla!'s aesthetics and usability into CiviCRM would improve the product, but having its own unique identity would be just as beneficial.</p>
<p>Consequently, this project will focus on building a strong design for CiviCRM and applying it not only to the UI but to the template system. Improving the underlying design would also improve the quality of the entire product. As a result, the project would begin with building a strong design and then shift to improving the UI and the template system using the new design standards.</p>
<p>Preliminary work would involve standards and design requirements. Documentation would be created to formalize the design process and ease future improvements to the theme. The documentation would also establish standards specific to CiviCRM and their unique needs. These documents would undergo thorough reviews before any further advancement on the project.</p>
<p>The design itself would rely heavily on HTML and CSS to provide a solid and flexible framework. Any changes would gracefully handle all major browsers with additional support for deprecated versions. It would also handle any possible accessibility issues, addressing concerns that arise from screen readers, scanning software and other methodology.</p>
<p>The template would also address the need for end user customization. In addition to being broken into modules that could be easily swapped by user created components, it would be easily adaptable and clearly commented for those desiring further customization. Additionally, the basic template would strive to provide even the most basic end user the ability to customize the theme. This could be achieved through something as simple as a color picker for the modules or a more complex user assembled puzzle piece approach to the template.</p>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}s:7:"content";a:1:{i:0;a:5:{s:4:"data";s:2191:"<blockquote>&quot;CiviCRM works great, but its visual design and layout could be better. Joomla! has great aesthetics and usability which would greatly benefit CiviCRM.&quot;</blockquote>
<p>&nbsp;</p>
<p>Integration will be a key to improving CiviCRM. Not only does it need to have its own distinct design, but it needs to integrate into Joomla! and feel as if it belongs. Integration of Joomla!'s aesthetics and usability into CiviCRM would improve the product, but having its own unique identity would be just as beneficial.</p>
<p>Consequently, this project will focus on building a strong design for CiviCRM and applying it not only to the UI but to the template system. Improving the underlying design would also improve the quality of the entire product. As a result, the project would begin with building a strong design and then shift to improving the UI and the template system using the new design standards.</p>
<p>Preliminary work would involve standards and design requirements. Documentation would be created to formalize the design process and ease future improvements to the theme. The documentation would also establish standards specific to CiviCRM and their unique needs. These documents would undergo thorough reviews before any further advancement on the project.</p>
<p>The design itself would rely heavily on HTML and CSS to provide a solid and flexible framework. Any changes would gracefully handle all major browsers with additional support for deprecated versions. It would also handle any possible accessibility issues, addressing concerns that arise from screen readers, scanning software and other methodology.</p>
<p>The template would also address the need for end user customization. In addition to being broken into modules that could be easily swapped by user created components, it would be easily adaptable and clearly commented for those desiring further customization. Additionally, the basic template would strive to provide even the most basic end user the ability to customize the theme. This could be achieved through something as simple as a color picker for the modules or a more complex user assembled puzzle piece approach to the template.</p>";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:74:"http://developer.joomla.org/gsoc2008/civicrm-aesthetics-and-usability.feed";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:5:"en-gb";}}}}}}}}}}}}s:7:"headers";a:13:{s:4:"date";s:29:"Sat, 25 Oct 2008 00:20:10 GMT";s:6:"server";s:78:"Apache/2.0.63 (Unix) mod_ssl/2.0.63 OpenSSL/0.9.7a mod_bwlimited/1.4 PHP/5.2.6";s:12:"x-powered-by";s:9:"PHP/5.2.6";s:10:"set-cookie";s:73:"e523959a7800415deda43fd5f0adee6b=f3f209e8a6b152c692816c4f206037b3; path=/";s:3:"p3p";s:48:"CP=NOI ADM DEV PSAi COM NAV OUR OTRo STP IND DEM";s:16:"content-encoding";s:4:"gzip";s:20:"x-content-encoded-by";s:11:"Joomla! 1.5";s:7:"expires";s:28:"Mon, 1 Jan 2001 00:00:00 GMT";s:13:"last-modified";s:29:"Sat, 25 Oct 2008 00:20:11 GMT";s:13:"cache-control";s:62:"no-store, no-cache, must-revalidate, post-check=0, pre-check=0";s:6:"pragma";s:8:"no-cache";s:14:"content-length";s:4:"6442";s:12:"content-type";s:35:"application/atom+xml; charset=utf-8";}s:5:"build";i:20080315205903;}