<?php
function static_block_block_info() {
    global $base_url; 
    $blocks['crm-solution-block1'] = array(
                                           'info' => t('crm-solution1'),
                                           'region' => 'content',
                                           'status' => 1,
                                           'cache' =>DRUPAL_NO_CACHE,
                                           'visibility' => BLOCK_VISIBILITY_LISTED,  
                                           'pages' =>"<front>\nfeature/*"
                                           );
    
    $blocks['get-started-homepage-block1'] = array(
                                                   'info' => t('get-started-homepage1'),
                                                   'region' => 'content',
                                                   'status' => 1,
                                                   'cache' =>DRUPAL_NO_CACHE,
                                                   'visibility' => BLOCK_VISIBILITY_LISTED,  
                                                   'pages' =>"<front>\nfeature/*"
                                                   );
    
    $blocks['homepage-joinus-block1'] = array(
                                              'info' => t('homepage-joinus1'),
                                              'region' => 'content',
                                              'status' => 1,
                                              'cache' =>DRUPAL_NO_CACHE,
                                              'visibility' => BLOCK_VISIBILITY_LISTED,  
                                              'pages' =>"<front>\nfeature/*"
                                              );
    $blocks['footer_custom'] = array(
                                              'info' => t('footer_custom_block1'),
                                              'region' => 'footer',
                                              'status' => 1,
                                              'cache' =>DRUPAL_NO_CACHE,
                                              );
   $blocks['what_is_civi'] = array(
                                              'info' => t('what is civicrm'),
                                              'region' => 'sidebar_first',
                                              'status' => 1,
                                              'cache' =>DRUPAL_NO_CACHE,
                                              'visibility' => BLOCK_VISIBILITY_LISTED,  
                                              'pages' =>"what\nwhat/*\nwhats/*\ncontent/*\ncomplete-expert"
                                              );

   $blocks['will_CiviMeet_needs'] = array(
                                              'info' => t('Will CiviCRM Meet Your Needs?'),
                                              'region' => 'sidebar_first',
                                              'status' => 1,
                                              'cache' =>DRUPAL_NO_CACHE,
                                              'visibility' => BLOCK_VISIBILITY_LISTED,  
                                              'pages' =>"features\nfeatures/*"
                                              );
   $blocks['get_started'] = array(
                                              'info' => t('Get Started'),
                                              'region' => 'sidebar_first',
                                              'status' => 1,
                                              'cache' =>DRUPAL_NO_CACHE,
                                              'visibility' => BLOCK_VISIBILITY_LISTED,  
                                              'pages' =>"go\ngo/*"
                                              );
   $blocks['participate_block'] = array(
                                              'info' => t('participate'),
                                              'region' => 'sidebar_first',
                                              'status' => 1,
                                              'cache' =>DRUPAL_NO_CACHE,
                                              'visibility' => BLOCK_VISIBILITY_LISTED,  
                                              'pages' =>"participate\nparticipate/*\nmih\ncontribute"
                                              );
   $blocks['casestudy_page_block'] = array(
                                              'info' => t('Casestudy Page Block'),
                                              'region' => 'sidebar_first',
                                              'status' => 1,
                                              'cache' =>DRUPAL_NO_CACHE,
                                              'visibility' => BLOCK_VISIBILITY_LISTED,  
                                              'pages' =>"casestudy/*/*"
                                              );
 $blocks['blog-news_block'] = array(
                                              'info' => t('Blog-News Block'),
                                              'region' => 'sidebar_first',
                                              'status' => 1,
                                              'cache' =>DRUPAL_NO_CACHE,
                                              'visibility' => BLOCK_VISIBILITY_LISTED,  
                                              'pages' =>"blog-new\nblog-new/*\nblog-news\nblog-news/*\nblogs\nblogs/*\ncategory\ncategory/*\ncomment\ncomment/*"
                                              );

 $blocks['expert_tab_block'] = array(
                                              'info' => t('expert tab block'),
                                              'region' => '-1',
                                              'status' => 1,
                                              'cache' =>DRUPAL_NO_CACHE,
                                             
                                              );
    return $blocks;
  }



function static_block_block_view($delta = '') {
    global $base_url; 
    $block = array();
    switch ($delta) {
    case 'crm-solution-block1':
        $block['title'] = 'A Fully Integrated CRM Solution';
        $block['subject'] = t('crm-solution');
        $crm_solution_block1 = module_invoke('views', 'block_view', 'sub_menu_block-block');
        $crm_solution_block2 = module_invoke('ddblock', 'block_view', 1);
        $block['content'] = render($crm_solution_block1);
        $block['content'] .= $crm_solution_block2['content'];
        return $block;

    case 'get-started-homepage-block1':
        $block['title'] = 'Get Started';
        $block['subject'] = t('get-started-homepage');
        $get_started_homepage_block1 = module_invoke('quicktabs', 'block_view', 'tabs');
        $block['content'] = render($get_started_homepage_block1);

        // $output = NULL;
        // $output .= '<p class="get-started-first">CiviCRM helps organizations grow and sustain strong relationships
        //     over time.</p>';
        // $output .= '<p class="get-started">This open source, Web-based platform helps organizations realize their missions through fundraising, events management, mass-mail marketing, peer-to-peer campaigns and more via one unified solution.</p>';
        // $output .= '<p class="get-started-last">CiviCRM&rsquo;s community is committed to the public good and has created a reliable network of international resources for hosting, developing and supporting this effective solution.</p>';

        $block['content'] .= $output;
        return $block; 
    case 'homepage-joinus-block1':
        $block['title'] = 'Join Us';
        $block['subject'] = t('homepage-joinus');
        $output = NULL;
        $output .= '<table class="three-tab">
             <tr>
             <td class="news-col">
             <h2>NEWS</h2>';
        
        $get_started_homepage_block1 = module_invoke('views', 'block_view', 'blog_news-block');
        $output .= render($get_started_homepage_block1);
        $output .='</td>
                  <td class="events-col">
                  <h2>EVENTS</h2>';
       $get_started_homepage_block2 = module_invoke('views', 'block_view', 'civi_upcoming_events-block');
        $output .= render($get_started_homepage_block2);
        $output .= '</td>
                    <td class="dev-col">
                     <h2>FOR DEVELOPERS</h2>';
        
        $get_started_homepage_block3 = module_invoke('menu', 'block_view', 'menu-for-developers');
        $output .= render($get_started_homepage_block3);
        $output .=  '</td>
                   </tr>
               </table>';
        
        //  $block['content'] = $get_started_homepage_block1['content'];
        $block['content'] = $output;
         return $block;
     case 'footer_custom':
         $block['title'] = NULL;
         //  $block['subject'] = t('footer-block');
         $output = NULL;
         $output .= '<table width="940" border="0" cellspacing="0" cellpadding="0" class="footer-tab">
                       <tr>
                        <td width="161px" valign="top"><h2><span class="gray">CIVI</span><span class="white">CRM</span></h2><br />
                          <h2 class="slogan">GROWING AND SUSTAINING RELATIONSHIPS</h2></td>
                         <td valign="top">';
         $output .= "<a  class='head-bottom' href=".$base_url."/what/whatiscivicrm><strong><span>WHAT IS CIVICRM</span></strong></a>";
         $footer_custom1  = module_invoke('menu', 'block_view', 'menu-footer-what-is-civicrm-subm');
          $output .= render($footer_custom1);
          $output .="</td>
                    <td valign='top'>";
          $output .="<a  class='head-bottom' href=".$base_url."/features><strong><span>WILL CIVICRM MEET YOUR NEEDS?</span></strong></a>"; 

          $footer_custom2 = module_invoke('menu', 'block_view', 'menu-footer-will-civicrm-meet-yo');
         $output .= render($footer_custom2);
         $output .="</td>
                    <td valign='top'>";
         $output .= "<a  class='head-bottom' href=".$base_url."/go><strong><span>GET STARTED</span></strong></a>"; 
         $footer_custom3 = module_invoke('menu', 'block_view', 'menu-footer-get-started');
         $output .= render($footer_custom3);
         $output .="</td>
                    <td valign='top'>";
         $output .= "<a  class='head-bottom' href=".$base_url."/participate><strong><span>PARTICIPATE</span></strong></a>"; 
         $footer_custom4  = module_invoke('menu', 'block_view', 'menu-footer-participate');
         $output .= render($footer_custom4);
             $output .= '</td>
                        </tr>
         </table>';
         $block['content'] = $output;

        return $block; 
        
    case 'what_is_civi':
        $block['title'] = NULL;
        $output = NULL;
        $output .= '<h1 class="what-civicrm"><a href="/what/whatiscivicrm">What is CiviCRM </a></h1>';
        $block['content'] = $output;
        return $block; 
    case 'will_CiviMeet_needs':
        $block['title'] = NULL;
        $output = NULL;
        $output .= '<h1 class="will-civicrm"><a href="/features">Will CiviCRM meet your needs? </a></h1>';
        $block['content'] = $output;
        return $block; 

     case 'get_started':
        $block['title'] = NULL;
        $output = NULL;
        $output .= '<h1 class="get-started-static">	<a href="/go">Get Started </a></h1>';
        $block['content'] = $output;
        return $block; 
    case 'participate_block':
        $block['title'] = NULL;
        $output = NULL;
        $output .= '<h1 class="participate"><a href="/participate">Participate</a></h1>';
        $block['content'] = $output;
        return $block;
    case 'casestudy_page_block':
        $block['title'] = NULL;
        $output = NULL;
        $output .= '<h1 class="case-study-page-block"><a href="/what/casestudies">Case Studies</a></h1>';
        $block['content'] = $output;
        return $block;
    case 'blog-news_block':
        $block['title'] = NULL;
        $output = NULL;
        $output .= '<h1 class="case-study-page-block"><a href="/blog-news">Blog</a></h1>';
        $block['content'] = $output;
        return $block;
    case 'expert_tab_block':
        $block['title'] = NULL;
        $output = NULL;
        $export = module_invoke('views', 'block_view', '-exp-complete_expert-page_2');
        $output .= render( $export );
        $output .= '<div class= "expert-tab"><a href = "/what/experts">' ."SEE COMPLETE LIST OF EXPERTS...". '</a></div>';
        $block['content'] = $output;
        return $block;
    }
}
