<?php
/**
 * Add menu item
 *
 * @return array
 */
function cividownload_menu() {
  $items = array();
  $items['download'] = array(
    'title' => t('CiviCRM Downloads'),
    'page callback' => 'cividownload_download_page',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['admin/config/content/cividownload'] = array(
    'title' => 'CiviDowload module settings',
    'description' => 'Set the CiviCRM version that is available for download',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cividownload_settings'),
    'access arguments' => array('administer modules'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function cividownload_download_page() {
  // check for download mode
  $download_mode = variable_get('cividownload_mode');
  if ($download_mode == 2 && arg(1) != 'list' ) { 
    $campaign_page = variable_get('campaign_page_url', '/campaign46');
    drupal_goto($campaign_page);
  }

  drupal_add_css(drupal_get_path('module', 'cividownload') . '/cividownload.css', array('weight' => 1000));

  $content = cividownload_download_list();
  return theme('cividownload_custompage_template', array('content' => $content));
}

function cividownload_download_list() {
  drupal_set_title('Download CiviCRM');

  // contribution page
  $url = '/civicrm/contribute/transact?reset=1&id=63&cms=';

  // build urls for the releases
  $content['download_urls'] = array(
    'drupal' => array(
      'title' => t('Drupal 7.x'),
      'url' => "{$url}drupal",
      'filename' => 'drupal.tar.gz',
    ),
    'drupal6' => array(
      'title' => t('Drupal 6.x'),
      'url' => "{$url}drupal6",
      'filename' => 'drupal6.tar.gz',
    ),
    'joomla' => array(
      'title' => t('Joomla 2.5.x / 3.x'),
      'url' => "{$url}joomla",
      'filename' => 'joomla.zip',
    ),
    'wordpress' => array(
      'title' => t('WordPress 3.x / 4.x'),
      'url' => "{$url}wordpress",
      'filename' => 'wordpress.zip',
    ),
  );

  $content['civicrm_version'] = _cividownload_get_current_version('stable');
  $content['civicrm_lts_version'] = _cividownload_get_current_version('lts');

  return $content;
}

function cividownload_theme($existing, $type, $theme, $path) {
  return array(
    'cividownload_custompage_template' => array(
      'template' => 'cividownload',
      'arguments' => array(),
    ),
  );
}

function _cividownload_get_current_version($releaseType = 'stable') {
  // Get all versions from JSON
  static $versions;
  if (!$versions) {
    $json = file_get_contents('http://latest.civicrm.org/versions.json');
    $versions = json_decode($json, TRUE);
  }

  // Sort major versions in reverse, so we can start with the newest.
  $major_versions = array_keys($versions);
  usort($major_versions, 'version_compare');
  $sorted_major_versions = array_reverse($major_versions);

  // Starting with newest major version, find the first one matching $releaseType
  foreach ($sorted_major_versions as $major_version) {
    if ($versions[$major_version]['status'] == $releaseType) {
      // Get the latest release in this version.
      return _cividownload_get_latest_release($versions[$major_version]['releases']);
    }
  }
}

function cividownload_settings() {
  $form = array();

  $options = array(
    1 => t('Regular download page'),
    2 => t('Campaign page'),
  );

  $form['cividownload_mode'] = array(
    '#type' => 'radios',
    '#title' => t('Download mode'),
    '#default_value' => variable_get('cividownload_mode', '1'),
    '#options' => $options,
    '#description' => t('Select "Campaign page" during fundraising period else "Regular download page"'),
    '#required' => TRUE,
  );

  $form['campaign_page_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Campaign page url'),
    '#default_value' => variable_get('campaign_page_url', 'campaign46'),
    '#size' => 30,
    '#description' => t('Enter internal node url. For eg: campaign46'),
    '#element_validate' => array('campaign_page_validate'),
  );

  return system_settings_form($form);
}

function campaign_page_validate($element, &$form_state) {
  if ($form_state['values']['cividownload_mode'] == 2 && empty($element['#value'])) {
    form_error($element, t('Please set campaign page url.'));
  }
}

/**
 * Implementation of CiviCRM's config hook
 * @param null $config
 */
function cividownload_civicrm_config(&$config = NULL) {
  static $configured = FALSE;
  if ($configured) {
    return;
  }
  $configured = TRUE;

  $template =& CRM_Core_Smarty::singleton();

  $extRoot = dirname(__FILE__) . DIRECTORY_SEPARATOR;
  $extDir = $extRoot . 'templates';

  if (is_array($template->template_dir)) {
    array_unshift($template->template_dir, $extDir);
  }
  else {
    $template->template_dir = array($extDir, $template->template_dir);
  }

  $include_path = $extRoot . PATH_SEPARATOR . get_include_path();
  set_include_path($include_path);
}


/**
 * Implementation of CiviCRM's buildForm hook to modify contribution page
 */
function cividownload_civicrm_buildForm($formName, &$form) {
  if ($formName == 'CRM_Contribute_Form_Contribution_Main' && $form->_id == 63) {
    drupal_set_title('');
    // add require js and css files
    drupal_add_library('system', 'ui.slider');
    drupal_add_css(drupal_get_path('module', 'cividownload') . '/cividownload.css', array('weight' => 1000));
    drupal_add_js(drupal_get_path('module', 'cividownload') . '/cividownload.js', array('weight' => 1000));

    // set page title
    $pageTitle = "Support CiviCRM"; 
    
    // get the source from the url
    $src = CRM_Utils_Request::retrieve('src', 'String', $form);
    if (!empty($src)) {
      if (!in_array($src, array('download'))) {
        CRM_Core_Error::fatal('Invalid src option');
      }
      $form->add('hidden', 'source', $src);
    }

    // get the filename from the url
    $cms = CRM_Utils_Request::retrieve('cms', 'String', $form);

    if ($cms) {
      if (!in_array($cms, array('drupal','drupal6','joomla','wordpress'))) {
        CRM_Core_Error::fatal('Invalid CMS option');
      }

      // check if it's a lts release
      $releaseType = CRM_Utils_Request::retrieve('rtype', 'String', $form);
      if (!empty($releaseType) && !in_array($releaseType, array('lts'))) {
        CRM_Core_Error::fatal('Invalid type');
      }

      // if type
      if (!empty($releaseType) && $releaseType == 'lts') {
        //get the current lts version
        $current_version = _cividownload_get_current_version('lts');
      }
      else {
        //get the current stable version
        $current_version = _cividownload_get_current_version();
      }

      switch ($cms) {
        case 'drupal':
          $cmsType = "Drupal 7.x";
          $fileName = "civicrm-{$current_version}-drupal.tar.gz";
          break;
        case 'drupal6':
          $cmsType = "Drupal 6.x";
          $fileName = "civicrm-{$current_version}-drupal6.tar.gz";
          break;
        case 'joomla':
          $cmsType = "Joomla 2.5.x / 3.x";
          $fileName = "civicrm-{$current_version}-joomla.zip";
          break;
        case 'wordpress':
          $cmsType = "Wordpress 3.x";
          $fileName = "civicrm-{$current_version}-wordpress.zip";
          break;
      }

      $form->assign('downloadURL', "https://download.civicrm.org/{$fileName}?src=donate");
      $pageTitle = "Downloading CiviCRM {$current_version} for {$cmsType} ({$fileName})";
    }
    $form->assign('pageTitle', $pageTitle);
  }
  elseif ($formName == 'CRM_Contribute_Form_Contribution_ThankYou' && $form->_id == 63) {
    if (!empty($form->_params['source']) && $form->_params['source'] == 'download') {
      // auto redirection js
      drupal_add_js(drupal_get_path('module', 'cividownload') . '/cividownload-redirect.js', array('weight' => 1000));

    }
  } 
}

/**
 * Determine the greatest version number among a given set of releases from
 * a version in versions.json
 *
 * @param Array $releases An array generated from the 'releases' property of
 *  a version in versions.json
 * 
 * @return String
 */
function _cividownload_get_latest_release($releases) {
  $release_versions = array();
  foreach($releases as $release) {
    $release_versions[] = $release['version'];
  }
  usort($release_versions, 'version_compare');
  return array_pop($release_versions);
}