<?php
// $Id: smfforum.install,v 1.2.2.3 2009/09/02 16:25:19 vb Exp $
/**
 * Copyright (Ñ) 2007-2008 by Vadim G.B. (http://vgb.org.ru)
 */

/**
 * Implementation of hook_install().
 */
//function smfforum_install() {
//}

/**
 * Implementation of hook_uninstall().
 */

function smfforum_uninstall() {

  // Delete all the smfforum variables and then clear the variable cache
 
  db_query("DELETE FROM {variable} WHERE name LIKE 'phpbbforum_%'");
  
  cache_clear_all('variables', 'cache');

  drupal_set_message(t('SMFforum module uninstalled successfully.'));
}